import { chromium } from '@playwright/test'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 412, height: 900 }, colorScheme: 'dark' })
await page.goto('http://localhost:4599', { waitUntil: 'networkidle' })
await page.getByText('Découvrir avec la famille de Wint').click()
await page.waitForTimeout(500)
await page.goto('http://localhost:4599/#/wint')
await page.waitForTimeout(500)
// Simule la mise à l'échelle de police Android (150 %)
await page.evaluate(() => { document.documentElement.style.fontSize = '24px' })
await page.waitForTimeout(300)
await page.getByText('MES NOTIFICATIONS', { exact: false }).scrollIntoViewIfNeeded()
await page.waitForTimeout(200)
await page.screenshot({ path: process.env.SP + '/scale-repro.png' })
await browser.close()
